[build]
  base = "FRONTEND"
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = ".netlify/v1/functions"

[build.environment]
  VITE_API_BASE_URL = "http://13.49.67.218:8000"
